apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: mysql
  DATASOURCE_URL: jdbc:mysql://petclinic-mysql-server.mysql.database.azure.com:3306/petclinic?useSSL=false&serverTimezone=UTC
  DATASOURCE_USERNAME: root_pet
  DATASOURCE_PASSWORD: Password1
  WEB_APP_ENDPOINT: http://web:8080
  VETS_SERVICE_ENDPOINT: http://vets:8080
  VISITS_SERVICE_ENDPOINT: http://visits:8080
  CUSTOMERS_SERVICE_ENDPOINT: http://customers:8080
