apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: idhar-read-pods
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pods-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: idhar-read-pods
subjects:
- kind: ServiceAccount
  name: idhar
  namespace: default

